### ISSUE TITLE
Checklist for unimplemented features during the jam

### ISSUE THREAD

**Issue by maxeonyx** [Maxeonyx/game-jam-home-is-where-the-heart-is#1]
- [ ] Keyboard + mouse support

- [ ] tweak friction to feel more realistic

- [ ] blood vessel levels with white blood cells and particle effects

- [ ] rope attachment

- [x] fix windows build on itch.io
